#!/bin/sh
set -eu

case ${SSH_ORIGINAL_COMMAND:-} in
  preflight|deploy|rollback-last)
    exec sudo -n /usr/local/sbin/anomaly-platform-deploy "$SSH_ORIGINAL_COMMAND"
    ;;
  *)
    echo "Only preflight, deploy, and rollback-last are permitted" >&2
    exit 64
    ;;
esac
